name: Publish binaries to release

# Workflow's trigger
on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1.3.0
    
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    
#     - name: Build
#       uses: actions-rs/cargo@v1.0.1
#       with:
#         # Cargo command to run (ex. `check` or `build`)
#         command: build
#         # Arguments for the cargo command
#         args: --release
#       env:
#         CARGO_PROFILE_RELEASE_LTO: true

    - name: Upload artifact and release
      uses: SOVLOOKUP/action-upload-artifacts-and-release-assets@main
      with:
        path: |
          target/release/*.so
          target/release/*.dll
          target/release/*.dylib
        upload-release-files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
